(()=>{const $=id=>document.getElementById(id),ok=window.supabase&&window.YAGELA_SUPABASE_URL&&window.YAGELA_SUPABASE_ANON_KEY&&!window.YAGELA_SUPABASE_URL.includes("YOUR-PROJECT")&&!window.YAGELA_SUPABASE_ANON_KEY.includes("YOUR_SUPABASE");if(!ok){$("loginError").textContent="Configure supabase-config.js first.";return}const db=window.supabase.createClient(window.YAGELA_SUPABASE_URL,window.YAGELA_SUPABASE_ANON_KEY),cats={personal:"Personal Care",home:"Household",fashion:"Fashion",ppe:"Engineering PPE",fragrance:"Fragrance",juice:"Fresh Juice"},money=n=>`GH₵ ${Number(n||0).toFixed(2)}`,esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c])),dt=v=>v?new Date(v).toLocaleString():"—";let products=[],orders=[],subs=[];
function toast(m){$("toast").textContent=m;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2400)}
function view(n){document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));$("view-"+n).classList.remove("hidden");document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===n));$("viewTitle").textContent=n[0].toUpperCase()+n.slice(1);if(n==="products")loadProducts();if(n==="orders")loadOrders();if(n==="subscribers")loadSubs()}
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>view(b.dataset.view));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>view(b.dataset.go));
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginError").textContent="";const {data,error}=await db.auth.signInWithPassword({email:$("loginEmail").value.trim(),password:$("loginPassword").value});if(error)$("loginError").textContent=error.message;else show(data.user)};
$("logoutBtn").onclick=async()=>{await db.auth.signOut();location.reload()};async function init(){const {data:{session}}=await db.auth.getSession();if(session)show(session.user)}function show(u){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("userEmail").textContent=u.email||"";refresh()}
async function loadProducts(){const {data,error}=await db.from("products").select("*").order("sort_order").order("created_at",{ascending:false});if(error)return toast(error.message);products=data||[];$("statProducts").textContent=products.filter(x=>x.active).length;renderProducts()}
function renderProducts(){const q=$("productSearch").value.toLowerCase(),c=$("productFilter").value,r=products.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(!c||p.category===c));$("productsTable").innerHTML=r.map(p=>`<tr><td><div class="product-cell"><img class="product-thumb" src="${esc(p.image_url||"../assets/placeholder.jpg")}"><div><strong>${esc(p.name)}</strong><br><small>${esc(p.description||"")}</small></div></div></td><td>${esc(cats[p.category]||p.category)}</td><td>${money(p.price)}</td><td><span class="badge ${p.active?"":"off"}">${p.active?"Active":"Hidden"}</span></td><td><div class="actions"><button class="ghost ep" data-id="${p.id}">Edit</button><button class="ghost danger dp" data-id="${p.id}">Delete</button></div></td></tr>`).join("")||'<tr><td colspan="5">No products found.</td></tr>';document.querySelectorAll(".ep").forEach(b=>b.onclick=()=>openProduct(b.dataset.id));document.querySelectorAll(".dp").forEach(b=>b.onclick=()=>delProduct(b.dataset.id))}
$("productSearch").oninput=renderProducts;$("productFilter").onchange=renderProducts;
function openProduct(id){$("productModal").classList.remove("hidden");$("productForm").reset();$("productId").value=id||"";$("pActive").checked=true;$("modalTitle").textContent=id?"Edit product":"Add product";if(id){const p=products.find(x=>x.id===id);$("pName").value=p.name;$("pCategory").value=p.category;$("pPrice").value=p.price;$("pBadge").value=p.badge||"";$("pImage").value=p.image_url||"";$("pSort").value=p.sort_order||0;$("pDescription").value=p.description||"";$("pActive").checked=p.active}}
function closeModal(){$("productModal").classList.add("hidden")}$("addProductBtn").onclick=()=>openProduct();$("closeProductModal").onclick=closeModal;$("cancelProduct").onclick=closeModal;
$("productForm").onsubmit=async e=>{e.preventDefault();const id=$("productId").value,p={name:$("pName").value.trim(),category:$("pCategory").value,price:Number($("pPrice").value),badge:$("pBadge").value.trim()||null,image_url:$("pImage").value.trim()||null,sort_order:Number($("pSort").value)||0,description:$("pDescription").value.trim()||null,active:$("pActive").checked};const r=id?await db.from("products").update(p).eq("id",id):await db.from("products").insert(p);if(r.error)toast(r.error.message);else{closeModal();toast("Product saved");loadProducts()}}
async function delProduct(id){if(!confirm("Delete this product?"))return;const {error}=await db.from("products").delete().eq("id",id);if(error)toast(error.message);else{toast("Product deleted");loadProducts()}}
async function loadOrders(){const {data,error}=await db.from("orders").select("*").order("created_at",{ascending:false});if(error)return toast(error.message);orders=data||[];renderOrders();stats()}
function renderOrders(){const f=$("orderStatusFilter").value,r=orders.filter(o=>!f||o.status===f);$("ordersTable").innerHTML=r.map(o=>`<tr><td><strong>${esc(o.customer_name)}</strong><br><small>${esc(o.customer_phone)}</small></td><td>${Array.isArray(o.items)?o.items.reduce((s,i)=>s+Number(i.quantity||1),0):"—"}</td><td>${money(o.total)}</td><td>${esc(o.payment_method)}</td><td><select class="status os" data-id="${o.id}"><option ${o.status==="pending"?"selected":""}>pending</option><option ${o.status==="processing"?"selected":""}>processing</option><option ${o.status==="completed"?"selected":""}>completed</option><option ${o.status==="cancelled"?"selected":""}>cancelled</option></select></td><td>${dt(o.created_at)}</td></tr>`).join("")||'<tr><td colspan="6">No orders found.</td></tr>';document.querySelectorAll(".os").forEach(s=>s.onchange=async()=>{const {error}=await db.from("orders").update({status:s.value}).eq("id",s.dataset.id);if(error)toast(error.message);else{toast("Order updated");loadOrders()}})}
$("orderStatusFilter").onchange=renderOrders;$("refreshOrders").onclick=loadOrders;
async function loadSubs(){const {data,error}=await db.from("subscribers").select("*").order("created_at",{ascending:false});if(error)return toast(error.message);subs=data||[];$("statSubscribers").textContent=subs.length;$("subscribersTable").innerHTML=subs.map(s=>`<tr><td><strong>${esc(s.email)}</strong></td><td>${dt(s.created_at)}</td></tr>`).join("")||'<tr><td colspan="2">No subscribers yet.</td></tr>'}$("refreshSubscribers").onclick=loadSubs;
function stats(){$("statOrders").textContent=orders.length;$("statRevenue").textContent=money(orders.filter(o=>o.status!=="cancelled").reduce((s,o)=>s+Number(o.total||0),0));$("recentOrders").innerHTML=orders.slice(0,8).map(o=>`<tr><td>${esc(o.customer_name)}</td><td>${money(o.total)}</td><td>${esc(o.payment_method)}</td><td><span class="badge">${esc(o.status)}</span></td><td>${dt(o.created_at)}</td></tr>`).join("")||'<tr><td colspan="5">No orders yet.</td></tr>'}async function refresh(){await Promise.all([loadProducts(),loadOrders(),loadSubs()])}init()})();